// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY
import HelloWorld from './HelloWorld.vue'
// Export components individually
export { HelloWorld }
// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('HelloWorld', HelloWorld)
}
// Export the library as a plugin
export default { install: install }
